export const LINKS = {
    LINK_TO_HOME_PAGE: 'LINK_TO_HOME_PAGE',
    LINK_TO_SEARCH_PAGE: 'LINK_TO_SEARCH_PAGE',
    LINK_TO_CHANNELS_PAGE: 'LINK_TO_CHANNELS_PAGE',
    LINK_TO_APPS_PAGE: 'LINK_TO_APPS_PAGE'
};
